apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-hw3.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otus-hw3.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "otus-hw3.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "otus-hw3.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8082
            initialDelaySeconds: 25
            periodSeconds: 20
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          env:
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATASOURCE_URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password