apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  type: NodePort
  selector:
    app: delivery-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-db-service
spec:
  type: NodePort
  selector:
    app: delivery-db-deployment
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-deployment
  template:
    metadata:
      labels:
        app: delivery-deployment
    spec:
      containers:
        - name: delivery
          image: vaomaohao/delivery:latest
          ports:
            - name: web
              containerPort: 8000
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: SERVER_PORT
            - name: DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: DATASOURCE_URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: DATASOURCE_PASSWORD
            - name: CAMUNDA_REST_API_URI
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: CAMUNDA_REST_API_URI
            - name: CAMUNDA_CLIENT_LOCK_DURATION
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: CAMUNDA_CLIENT_LOCK_DURATION
            - name: CAMUNDA_CLIENT_LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: delivery-configmap
                  key: CAMUNDA_CLIENT_LOGGING_LEVEL
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: delivery-db-deployment
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: delivery-db-deployment
  template:
    metadata:
      labels:
        app: delivery-db-deployment
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: DATASOURCE_PASSWORD
#          volumeMounts:
#            - name: postgredb
#              mountPath: /var/lib/postgresql/data
#              subPath: postgres
#  volumeClaimTemplates:
#    - metadata:
#        name: postgredb
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: standard
#        resources:
#          requests:
#            storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: delivery-secret
type: Opaque
data:
  DATASOURCE_USERNAME: YWRtaW4=
  DATASOURCE_PASSWORD: cGFzc3dvcmQ=
  DATABASE_NAME: ZGI=
  DATASOURCE_URL: "amRiYzpwb3N0Z3Jlc3FsOi8vZGVsaXZlcnktZGItc2VydmljZTo1NDMyL2RiP2N1cnJlbnRTY2hlbWE9b3R1cw=="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-configmap
data:
  SERVER_PORT: "8000"
  CAMUNDA_REST_API_URI: "http://order-service:8000/rest"
  CAMUNDA_CLIENT_LOCK_DURATION: "1000"
  CAMUNDA_CLIENT_LOGGING_LEVEL: "DEBUG"