server:
  port: 8082

spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: "\${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=otus}"
    username: "\${DATASOURCE_USERNAME:postgres}"
    password: "\${DATASOURCE_PASSWORD:postgres}"
  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  flyway:
    schemas: otus
    baseline-on-migrate: true

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
            percentiles: 0.5, 0.95, 0.99
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, logfile, prometheus
