{
 "title": "HW3",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Database lock count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"crud_app\"}"
    }
   ]
  },
  {
   "title": "Requests users service from nginx-ingress-controller",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_requests{exported_service=\"otus-hw3\"}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(rate(http_server_requests_seconds_sum{uri=\"/user\"}[3m]) / rate(http_server_requests_seconds_count{uri=\"/user\"}[3m]))"
    }
   ]
  },
  {
   "title": "Latency with quantiles on /user endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_server_requests_seconds{uri=\"/user\"}"
    }
   ]
  },
  {
   "title": "Memory usage (user service) (MiB) ",
   "type": "gauge",
   "description": "memory usage in MiB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"otus-hw3\", service=\"prometheus-kube-prometheus-kubelet\"} / (1024 * 1024 )"
    }
   ]
  },
  {
   "title": "CPU usage (user service) (millicores)",
   "type": "gauge",
   "description": "CPU usage in millicores",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{container=\"otus-hw3\", service=\"stable-prometheus-stack-ku-kubelet\"}[1m])"
    }
   ]
  }
 ]
}