apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: {{ include "hw5.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hw5.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 8082
      protocol: TCP
      name: web
  selector:
    {{- include "hw5.selectorLabels" . | nindent 4 }}