CREATE TABLE IF NOT EXISTS otus.order
(
    id             bigint PRIMARY KEY,
    version        int            NOT NULL DEFAULT 0,
    user_name      varchar        UNIQUE,
    sum_order      numeric(10, 2) NOT NULL DEFAULT 0
);

ALTER TABLE otus.order ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY;