apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-hw2.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otus-hw2.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    {{- include "otus-hw2.selectorLabels" . | nindent 4 }}