replicaCount: 1

image: vaomaohao/prometheus-grafana-stable:stable

resources:
  limits:
    cpu: "1000m"
    memory: "512Mi"
  requests:
    cpu: "500m"
    memory: "256Mi"

postgres:
  username: otus_user
  port: "5432"
  database: crud_app
  schema: otus
  host: postgres

ingress:
  host: "arch.homework"

metrics:
  serviceMonitor:
    enabled: true

## Custom values for postgresql chart
postgresql:

  primary:
    persistence:
      enabled: false

  auth:
    username: otus_user
    password: qwe123
    database: crud_app
  fullnameOverride: postgres

  service:
    type: NodePort
    port: 5432

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: otus-homework
      interval: 15s