apiVersion: v1
kind: Service
metadata:
  name: idempotency-service
spec:
  type: NodePort
  selector:
    app: idempotency-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: idempotency-db-service
spec:
  type: NodePort
  selector:
    app: idempotency-db-deployment
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idempotency-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idempotency-deployment
  template:
    metadata:
      labels:
        app: idempotency-deployment
    spec:
      containers:
        - name: idempotency
          image: vaomaohao/idempotency:latest
          ports:
            - name: web
              containerPort: 8000
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: idempotency-configmap
                  key: SERVER_PORT

            - name: DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: idempotency-secret
                  key: DATASOURCE_URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: idempotency-secret
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: idempotency-secret
                  key: DATASOURCE_PASSWORD
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: idempotency-db-deployment
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: idempotency-db-deployment
  template:
    metadata:
      labels:
        app: idempotency-db-deployment
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: idempotency-secret
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: idempotency-secret
                  key: DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: idempotency-secret
                  key: DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: idempotency-secret
type: Opaque
data:
  DATASOURCE_USERNAME: YWRtaW4=
  DATASOURCE_PASSWORD: cGFzc3dvcmQ=
  DATABASE_NAME: ZGI=
  DATASOURCE_URL: "amRiYzpwb3N0Z3Jlc3FsOi8vaWRlbXBvdGVuY3ktZGItc2VydmljZTo1NDMyL2RiP2N1cnJlbnRTY2hlbWE9b3R1cw=="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idempotency-configmap
data:
  SERVER_PORT: "8000"