server:
  port: "\${SERVER_PORT}"

spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: "\${DATASOURCE_URL}"
    username: "\${DATASOURCE_USERNAME}"
    password: "\${DATASOURCE_PASSWORD}"
  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  flyway:
    schemas: otus
    baseline-on-migrate: true

camunda:
  bpm:
    client:
      base-url: "\${CAMUNDA_REST_API_URI}"
      lock-duration: "\${CAMUNDA_CLIENT_LOCK_DURATION}"
      basic-auth:
        username: admin
        password: admin

logging:
  level:
    org:
      camunda:
        bpm:
          client: "\${CAMUNDA_CLIENT_LOGGING_LEVEL}"

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  endpoints:
    web:
      base-path: /